// <auto-generated />
using System;
using APBD_cw13.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APBD_cw13.Migrations
{
    [DbContext(typeof(SweetStoreDbContext))]
    partial class SweetStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("APBD_cw13.Models.Confectionary", b =>
                {
                    b.Property<int>("IdConfectionary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<float>("PricePerIte")
                        .HasColumnType("real");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.HasKey("IdConfectionary");

                    b.ToTable("Confectionary");

                    b.HasData(
                        new
                        {
                            IdConfectionary = 1,
                            Name = "Chocolate",
                            PricePerIte = 100f,
                            Type = "food"
                        },
                        new
                        {
                            IdConfectionary = 2,
                            Name = "Makowiec",
                            PricePerIte = 200f,
                            Type = "ciasto"
                        },
                        new
                        {
                            IdConfectionary = 3,
                            Name = "baklawa",
                            PricePerIte = 150f,
                            Type = "food"
                        });
                });

            modelBuilder.Entity("APBD_cw13.Models.Confectionary_Order", b =>
                {
                    b.Property<int>("IdConfection")
                        .HasColumnType("int");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("IdConfection", "IdOrder");

                    b.HasIndex("IdOrder");

                    b.ToTable("Confectionary_Order");

                    b.HasData(
                        new
                        {
                            IdConfection = 1,
                            IdOrder = 1,
                            Notes = "Bardzo dobre slodycze",
                            Quantity = 2
                        },
                        new
                        {
                            IdConfection = 2,
                            IdOrder = 1,
                            Notes = "Bardzo dobre",
                            Quantity = 4
                        },
                        new
                        {
                            IdConfection = 3,
                            IdOrder = 2,
                            Notes = "Smakowalo",
                            Quantity = 1
                        },
                        new
                        {
                            IdConfection = 3,
                            IdOrder = 3,
                            Notes = "Bardzo dobre",
                            Quantity = 14
                        },
                        new
                        {
                            IdConfection = 2,
                            IdOrder = 3,
                            Notes = "Bardzo dobre",
                            Quantity = 25
                        });
                });

            modelBuilder.Entity("APBD_cw13.Models.Customer_confectionary", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("IdClient");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            IdClient = 1,
                            FirstName = "Andrzej",
                            LastName = "Kowalski"
                        },
                        new
                        {
                            IdClient = 2,
                            FirstName = "Jan",
                            LastName = "Nowak"
                        },
                        new
                        {
                            IdClient = 3,
                            FirstName = "Ola",
                            LastName = "Gruszewska"
                        },
                        new
                        {
                            IdClient = 4,
                            FirstName = "Jan",
                            LastName = "Kazimierz"
                        });
                });

            modelBuilder.Entity("APBD_cw13.Models.Employee_confectionary", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("IdEmployee");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            IdEmployee = 1,
                            FirstName = "Ala",
                            LastName = "Kotowska"
                        },
                        new
                        {
                            IdEmployee = 2,
                            FirstName = "Dogumil",
                            LastName = "Januszewski"
                        },
                        new
                        {
                            IdEmployee = 3,
                            FirstName = "Julian",
                            LastName = "Gruszka"
                        });
                });

            modelBuilder.Entity("APBD_cw13.Models.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateAccepted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFinished")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdClient")
                        .HasColumnType("int");

                    b.Property<int?>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("IdOrder");

                    b.HasIndex("IdClient");

                    b.HasIndex("IdEmployee");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            IdOrder = 1,
                            DateAccepted = new DateTime(1999, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFinished = new DateTime(2000, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClient = 4,
                            IdEmployee = 1,
                            Notes = "Wszystko ok"
                        },
                        new
                        {
                            IdOrder = 2,
                            DateAccepted = new DateTime(1998, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFinished = new DateTime(2000, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClient = 1,
                            IdEmployee = 3,
                            Notes = "Wszystko ok"
                        },
                        new
                        {
                            IdOrder = 3,
                            DateAccepted = new DateTime(1998, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFinished = new DateTime(2000, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClient = 2,
                            IdEmployee = 2,
                            Notes = "Fajny personel!"
                        },
                        new
                        {
                            IdOrder = 4,
                            DateAccepted = new DateTime(1998, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateFinished = new DateTime(2000, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IdClient = 4,
                            IdEmployee = 3,
                            Notes = "Nie smakowalo :("
                        });
                });

            modelBuilder.Entity("APBD_cw13.Models.Confectionary_Order", b =>
                {
                    b.HasOne("APBD_cw13.Models.Confectionary", "Confectionary")
                        .WithMany("Confectionary_Orders")
                        .HasForeignKey("IdConfection")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_cw13.Models.Order", "Order")
                        .WithMany("Confectionary_Orders")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("APBD_cw13.Models.Order", b =>
                {
                    b.HasOne("APBD_cw13.Models.Customer_confectionary", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("APBD_cw13.Models.Employee_confectionary", "Employee")
                        .WithMany("Orders")
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
